name: Security Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    name: Security Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Install project dependencies
        run: poetry install

      - name: Install Bandit
        run: pip install bandit

      - name: Run Security Scans
        run: |
          # Run Bandit for static security analysis
          poetry run bandit -r . --exclude tests/*.py

          # Run Safety to check for vulnerable dependencies
          poetry run safety check

      # Add additional steps as needed for other security testing tools or checks
